import type { Project, Keyword, Analysis } from '@/types/database';

interface ReportData {
  project: Project;
  keywords: Keyword[];
  analyses: Analysis[];
}

export function generateProjectReport(data: ReportData): string {
  const { project, keywords, analyses } = data;
  const avgScore = analyses.length
    ? Math.round(analyses.reduce((sum, a) => sum + (a.score ?? 0), 0) / analyses.length)
    : null;

  const keywordRows = keywords
    .map(
      (kw) =>
        `<tr><td>${esc(kw.keyword)}</td><td>${kw.position ?? '—'}</td><td>${kw.search_volume ?? '—'}</td></tr>`
    )
    .join('');

  const analysisRows = analyses
    .map(
      (a) =>
        `<tr><td>${esc(a.url)}</td><td>${a.score ?? '—'}/100</td><td>${new Date(a.created_at).toLocaleDateString()}</td></tr>`
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>SEO Report — ${esc(project.name)}</title>
<style>
  body{font-family:system-ui,sans-serif;max-width:800px;margin:2rem auto;padding:0 1rem;color:#1a1a1a;background:#fff}
  h1{font-size:1.5rem;border-bottom:2px solid #e5e7eb;padding-bottom:.5rem}
  h2{font-size:1.1rem;margin-top:2rem;color:#4b5563}
  table{width:100%;border-collapse:collapse;margin:.5rem 0}
  th,td{text-align:left;padding:.5rem;border-bottom:1px solid #e5e7eb;font-size:.875rem}
  th{font-weight:600;color:#6b7280}
  .stat{display:inline-block;background:#f3f4f6;padding:.75rem 1.5rem;border-radius:.5rem;margin:.25rem;text-align:center}
  .stat-value{font-size:1.5rem;font-weight:700}
  .stat-label{font-size:.75rem;color:#6b7280}
  .footer{margin-top:3rem;padding-top:1rem;border-top:1px solid #e5e7eb;font-size:.75rem;color:#9ca3af}
</style>
</head>
<body>
<h1>SEO Report: ${esc(project.name)}</h1>
${project.url ? `<p>URL: ${esc(project.url)}</p>` : ''}
<p>Generated: ${new Date().toLocaleDateString()}</p>

<div>
  <div class="stat"><div class="stat-value">${keywords.length}</div><div class="stat-label">Keywords</div></div>
  <div class="stat"><div class="stat-value">${analyses.length}</div><div class="stat-label">Analyses</div></div>
  <div class="stat"><div class="stat-value">${avgScore !== null ? avgScore + '/100' : '—'}</div><div class="stat-label">Avg Score</div></div>
</div>

${keywords.length ? `<h2>Keywords</h2><table><thead><tr><th>Keyword</th><th>Position</th><th>Volume</th></tr></thead><tbody>${keywordRows}</tbody></table>` : ''}

${analyses.length ? `<h2>Analyses</h2><table><thead><tr><th>URL</th><th>Score</th><th>Date</th></tr></thead><tbody>${analysisRows}</tbody></table>` : ''}

<div class="footer">Generated by Auto-SEO</div>
</body>
</html>`;
}

export function exportKeywordsCsv(keywords: Keyword[]): string {
  const header = 'keyword,position,search_volume,created_at';
  const rows = keywords.map(
    (kw) => `"${kw.keyword}",${kw.position ?? ''},${kw.search_volume ?? ''},${kw.created_at}`
  );
  return [header, ...rows].join('\n');
}

export function exportAnalysesCsv(analyses: Analysis[]): string {
  const header = 'url,score,created_at';
  const rows = analyses.map((a) => `"${a.url}",${a.score ?? ''},${a.created_at}`);
  return [header, ...rows].join('\n');
}

function esc(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
